version: "3.3"
services:
  iNoi:
    restart: always
    volumes:
      - "/etc/inoi:/opt/inoi/data"
      # - "/你的数据文件夹:/media"
    ports:
      - "5244:5244"
      - "5245:5245"
    environment:
      - UMASK=022
      - TZ=UTC
    container_name: inoi
    user: 0:0
    image: "leolitaly/inoi:latest"
